# Generated by Django 6.0.1 on 2026-01-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='selected_option_id',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='response_id',
            new_name='response',
        ),
        migrations.RenameField(
            model_name='options',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='form_id',
            new_name='form',
        ),
        migrations.RenameField(
            model_name='responses',
            old_name='form_id',
            new_name='form',
        ),
    ]
